-- ============================================================
-- SIREGI - Setup Tabel Akun OwnCloud Cabang & Log Aktivitas
-- Jalankan script ini di Supabase Dashboard > SQL Editor
-- ============================================================

-- 1. Buat Tabel Akun OwnCloud Cabang
CREATE TABLE IF NOT EXISTS owncloud_cabang (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  cabang_id UUID UNIQUE NOT NULL REFERENCES cabang(id) ON DELETE CASCADE,
  email TEXT,
  username TEXT NOT NULL,
  password TEXT NOT NULL, -- Encrypted AES-GCM
  keterangan TEXT,
  status TEXT DEFAULT 'Aktif' CHECK (status IN ('Aktif', 'Nonaktif')),
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Kolom tambahan jika tabel sudah terlanjur dibuat
ALTER TABLE owncloud_cabang ADD COLUMN IF NOT EXISTS email TEXT;

-- RLS (Row Level Security) untuk owncloud_cabang
ALTER TABLE owncloud_cabang ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read owncloud_cabang" ON owncloud_cabang;
CREATE POLICY "Public can read owncloud_cabang" ON owncloud_cabang FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public can insert owncloud_cabang" ON owncloud_cabang;
CREATE POLICY "Public can insert owncloud_cabang" ON owncloud_cabang FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Public can update owncloud_cabang" ON owncloud_cabang;
CREATE POLICY "Public can update owncloud_cabang" ON owncloud_cabang FOR UPDATE USING (true);

DROP POLICY IF EXISTS "Public can delete owncloud_cabang" ON owncloud_cabang;
CREATE POLICY "Public can delete owncloud_cabang" ON owncloud_cabang FOR DELETE USING (true);

-- 2. Buat Tabel Log Aktivitas Admin
CREATE TABLE IF NOT EXISTS admin_activity_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_username TEXT NOT NULL,
  action TEXT NOT NULL, -- 'ADD', 'EDIT', 'DELETE'
  target_cabang TEXT NOT NULL,
  details TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS untuk admin_activity_log
ALTER TABLE admin_activity_log ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Public can read admin_activity_log" ON admin_activity_log;
CREATE POLICY "Public can read admin_activity_log" ON admin_activity_log FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public can insert admin_activity_log" ON admin_activity_log;
CREATE POLICY "Public can insert admin_activity_log" ON admin_activity_log FOR INSERT WITH CHECK (true);
