-- ============================================================
-- SIREGI: Setup Activity Logs Table
-- Tabel baru untuk mencatat aktivitas user (login, logout, heartbeat)
-- TIDAK mengubah tabel existing apapun
-- ============================================================

CREATE TABLE activity_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES app_users(id) ON DELETE CASCADE,
  activity_type TEXT NOT NULL,        -- LOGIN, LOGOUT, HEARTBEAT
  activity_time TIMESTAMPTZ DEFAULT NOW(),
  ip_address TEXT,                    -- Opsional
  user_agent TEXT,                    -- Browser/device info
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index untuk performa query
CREATE INDEX idx_activity_logs_user_id ON activity_logs(user_id);
CREATE INDEX idx_activity_logs_activity_time ON activity_logs(activity_time DESC);
CREATE INDEX idx_activity_logs_activity_type ON activity_logs(activity_type);

-- Enable RLS (Row Level Security)
ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;

-- Policy: Semua user bisa insert activity mereka sendiri
CREATE POLICY "Users can insert their own activity" 
  ON activity_logs FOR INSERT 
  WITH CHECK (true);

-- Policy: Semua user bisa membaca activity logs
CREATE POLICY "Users can read activity logs" 
  ON activity_logs FOR SELECT 
  USING (true);

-- Policy: Allow delete for cleanup (admin only via service role)
CREATE POLICY "Allow delete activity logs"
  ON activity_logs FOR DELETE
  USING (true);
